import type { ApiConfig } from '../types';

const MFDS_SHARED = {
  defaultParams: {
    type: 'json',
  },
  dataPath: ['body', 'items'],
  totalPath: ['body', 'totalCount'],
  errorCheck: {
    containerPaths: [['header']],
    codeKey: 'resultCode',
    messageKey: 'resultMsg',
    successValues: ['00', 'OK', 'INFO-0'],
  },
  note:
    '공공데이터포털에서 해당 API 활용승인을 받은 뒤 공용 API_SERVICE_KEY_PUBLIC(.호환: API_SERVICE_KEY)를 .env.local에 넣어 사용하세요.',
} satisfies Pick<ApiConfig, 'defaultParams' | 'dataPath' | 'totalPath' | 'errorCheck' | 'note'>;

export const mfdsApis: ApiConfig[] = [
  {
    ...MFDS_SHARED,
    id: 'imported-food-recall-stop',
    title: '수입식품 회수판매중지 제품 정보',
    category: '식품 · 회수/판매중지',
    endpoint:
      'https://apis.data.go.kr/1471000/IprtFoodReclSaleStopPrdtStusService/getIprtFoodReclSaleStopPrdtStusInq',
    labelMap: {
      PRDT_NM: '제품명',
      CLNT_BSSH_NM: '업체명',
      MNFT_YMD_RLAT_CONT: '제조일자',
      CIRC_PRD: '유통기한',
      RECL_RESN_CONT: '회수사유',
      RECL_MTH_CONT: '회수방법',
      PRMT_NO: '영업등록번호',
      PRCS_POTM_DTL_ADDR: '영업자주소',
      BRCD_NO: '바코드번호',
      PCKN_UNIT_INFO: '포장단위',
      RECL_COMND_DT: '등록일자',
      RECL_GRAD_CD_NM: '회수등급',
      PRDLST_NM: '식품분류',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'agricultural-product-test-failures',
    title: '검사부적합 현황(농산물)',
    category: '식품 · 검사부적합',
    endpoint:
      'https://apis.data.go.kr/1471000/PrsecImproptAgriprStusService/getPrsecImproptAgriprList',
    labelMap: {
      RTRVLDSUSE_SEQ: '회수/폐기 일련번호',
      PRDTNM: '제품명',
      BSSHNM: '업소명',
      MNFDT: '제조일자',
      DISTBTMLMT: '유통기한',
      ADDR: '주소',
      INSTT_NM: '검사기관',
      REGSTR_TELNO: '등록자 전화번호',
      REPORTR_TELNO: '신고자 전화번호',
      BRCDNO: '바코드번호',
      FRMLCUNIT: '포장단위',
      TEST_ITMNM: '부적합항목',
      STDR_STND: '기준규격',
      TESTANALS_RSLT: '검사결과',
      CRET_DTM: '등록일자',
      LCNS_NO: '인허가번호',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'easy-drug-info',
    title: '의약품개요정보(e약은요)',
    category: '의약품 · e약은요',
    endpoint:
      'https://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList',
    labelMap: {
      entpName: '업체명',
      itemName: '제품명',
      itemSeq: '품목기준코드',
      efcyQesitm: '효능',
      useMethodQesitm: '사용법',
      atpnWarnQesitm: '주의사항(경고)',
      atpnQesitm: '주의사항',
      intrcQesitm: '상호작용',
      seQesitm: '부작용',
      depositMethodQesitm: '보관법',
      openDe: '공개일자',
      updateDe: '수정일자',
      itemImage: '낱알이미지',
      bizrno: '사업자번호',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'dur-prdlst-info',
    title: '의약품안전사용서비스(DUR) 품목정보',
    category: '의약품 · DUR 품목',
    endpoint:
      'https://apis.data.go.kr/1471000/DURPrdlstInfoService03/getDurPrdlstInfoList03',
    labelMap: {
      ITEM_SEQ: '품목기준코드',
      ITEM_NAME: '제품명',
      ENTP_NAME: '업체명',
      ITEM_PERMIT_DATE: '허가일',
      ETC_OTC_CODE: '전문/일반구분',
      CLASS_NO: '분류번호',
      CHART: '성상',
      BAR_CODE: '바코드',
      MATERIAL_NAME: '원료성분',
      EE_DOC_ID: '효능 문서',
      UD_DOC_ID: '용법용량 문서',
      NB_DOC_ID: '주의사항 문서',
      INSERT_FILE: '첨부문서',
      STORAGE_METHOD: '보관방법',
      VALID_TERM: '유효기간',
      REEXAM_TARGET: '재심사대상',
      REEXAM_DATE: '재심사일자',
      PACK_UNIT: '포장단위',
      EDI_CODE: 'EDI 코드',
      CANCEL_DATE: '취소일자',
      CANCEL_NAME: '상태',
      TYPE_CODE: 'DUR 유형코드',
      TYPE_NAME: 'DUR 유형',
      CHANGE_DATE: '변경일자',
      BIZRNO: '사업자번호',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'dur-ingredient-info',
    title: '의약품안전사용서비스(DUR) 성분정보',
    category: '의약품 · DUR 성분',
    endpoint:
      'https://apis.data.go.kr/1471000/DURIrdntInfoService03/getCpctyAtentInfoList02',
    labelMap: {
      DUR_SEQ: 'DUR번호',
      TYPE_NAME: 'DUR유형',
      MIX_TYPE: '단일/복합',
      INGR_CODE: 'DUR성분코드',
      INGR_ENG_NAME: 'DUR성분(영문)',
      INGR_NAME: 'DUR성분',
      MIX_INGR: '복합제',
      ORI_INGR: '관계성분',
      CLASS_NAME: '효능군',
      FORM_NAME: '제형',
      MAX_QTY: '최대용량',
      NOTIFICATION_DATE: '고시일자',
      PROHBT_CONTENT: '금기내용',
      REMARK: '비고',
      DEL_YN: '상태',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'drug-administrative-disposition',
    title: '의약품 행정처분 정보',
    category: '의약품 · 행정처분',
    endpoint:
      'https://apis.data.go.kr/1471000/MdcinExaathrService04/getMdcinExaathrList04',
    defaultParams: {
      ...MFDS_SHARED.defaultParams,
      order: 'Y',
    },
    labelMap: {
      ADM_DISPS_SEQ: '행정처분일련번호',
      ENTP_NAME: '업체명',
      ADDR: '업체소재지',
      ENTP_NO: '업일련번호',
      ITEM_NAME: '제품명',
      BEF_APPLY_LAW: '위반법명',
      EXPOSE_CONT: '위반내용',
      ADM_DISPS_NAME: '행정처분명',
      LAST_SETTLE_DATE: '행정처분일자',
      ITEM_SEQ: '품목기준코드',
      RLS_END_DATE: '공개종료일자',
      BIZRNO: '사업자번호',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'cosmetic-regulation-info',
    title: '화장품 규제정보',
    category: '화장품 · 규제정보',
    endpoint:
      'https://apis.data.go.kr/1471000/CsmtcsReglMaterialInfoService/getCsmtcsReglMaterialInfoService',
    labelMap: {
      INGR_STD_NAME: '성분 표준명',
      INGR_ENG_NAME: '영문명',
      PROH_NATIONAL: '금지국가',
      LIMIT_NATIONAL: '제한국가',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'cosmetic-recall-stop',
    title: '화장품 회수·판매중지 정보',
    category: '화장품 · 회수/판매중지',
    endpoint:
      'https://apis.data.go.kr/1471000/CsmtcsRtrvlSleStpgeInfo/getCsmtcsRtrvlSleStpgeInfo',
    labelMap: {
      ENTP_NAME: '업체명',
      ADDR: '주소',
      ITEM_NAME: '품목명',
      DISPS_CONT: '회수사유',
      MAKE_NO: '제조번호',
      MAKE_DATE: '제조일자',
      VALID_DATE: '유효기간',
      TARGET_PACK_UNIT: '포장단위',
      APPROVAL_DATE: '승인일자',
      ETC: '비고',
      RECALL_COMMAND_DATE: '회수명령일자',
      OPEN_END_DATE: '공개마감일자',
      BIZRNO: '사업자번호',
    },
  },
  {
    ...MFDS_SHARED,
    id: 'functional-cosmetic-report-items',
    title: '기능성화장품 보고품목정보',
    category: '화장품 · 기능성 보고품목',
    endpoint:
      'https://apis.data.go.kr/1471000/FtnltCosmRptPrdlstInfoService/getRptPrdlstInq',
    labelMap: {
      COSMETIC_REPORT_SEQ: '보고일련번호',
      ITEM_SEQ: '품목일련번호',
      ITEM_NAME: '품목명',
      DEPT_RECEIPT_NO: '부서접수번호',
      REPORT_FLAG_CODE: '보고구분코드',
      REPORT_FLAG_NAME: '보고구분명',
      MANUF_NAME: '제조업자',
      MANUF_COUNTRY_CODE: '제조국가코드',
      MANUF_COUNTRY_NAME: '제조국가명',
      MANUF_PLACE: '제조원소재지',
      ITEM_PH: '품목PH',
      COSMETIC_TARGET_FLAG: '대상구분코드',
      COSMETIC_TARGET_FLAG_NAME: '대상구분명',
      COSMETIC_STD_CODE: '기준코드',
      COSMETIC_STD_NAME: '기준명',
      ENTP_NAME: '책임판매업자',
      ENTP_SEQ: '업체일련번호',
      REPORT_DATE: '보고일자',
      CANCEL_REQ_DATE: '취하요청일자',
      CANCEL_APPROVAL_DATE: '취하승인일자',
      CANCEL_APPROVAL_YN: '취하승인여부',
      ETHANOL_OVER_YN: '에탄올4%초과여부',
      EE_CODE: '효능효과코드',
      EE_NAME: '효능효과명',
      SPF: 'SPF',
      PA: 'PA',
      USAGE_DOSAGE: '용법용량',
      EFFECT_YN1: '미백기능성여부',
      EFFECT_YN2: '주름개선기능성여부',
      EFFECT_YN3: '자외선차단기능성여부',
      WATER_PROOFING_FLAG: '내수여부',
      WATER_PROOFING_NAME: '내수성',
      EE_DOC_DATA: '효능효과 문서',
      UD_DOC_DATA: '용법용량 문서',
      NB_DOC_DATA: '주의사항 문서',
      BIZRNO: '사업자번호',
    },
  },
];
